package:
  name: som-learn
  version: "0.1.1"

source:
  url: "https://files.pythonhosted.org/packages/0c/1e/623af267dd014bb28fe802ac942791bc9e1cc0330d97f1cfd26550a9fc2a/som-learn-0.1.1.tar.gz"
  sha256: "978494df479d43156a047d90935dfdda1664efa25daa4f2946a9e4304860d172"

build:
  number: 0
  noarch: python

requirements:
  host:
    - numpy >=1.1
    - pip
    - python
    - scikit-learn >=0.21
    - scipy >=0.17
    - matplotlib >=3.0
    - somoclu ==1.7.5

  run:
    - numpy >=1.1
    - python
    - scikit-learn >=0.21
    - scipy >=0.17
    - matplotlib >=3.0
    - somoclu ==1.7.5


test:
  requires:
    - coverage
    - pytest
    - pytest-cov
  imports:
    - somlearn

about:
  home: "https://github.com/AlgoWit/som-learn"
  license: "MIT"
  license_file: ""
